from snakemake.utils import validate

configfile : "config/workflowsettings.yaml"
validate(config,"schemas/config.schema.yaml")


"""
include all rules

common-rules is including 
"""

include: "rules/common.smk"
include: "rules/create.smk"
include: "rules/prep.smk"
include: "rules/execute.smk"
include: "rules/post.smk"


"""
When working in a cluster environment, not all rules need to become a job that has to be submitted 
(e.g. downloading some file, or a target-rule like all, see Targets and aggregation). 
The keyword localrules allows to mark a rule as local,
so that it is not submitted to the cluster and instead executed on the host node

https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#resources
"""

localrules: all, write_caseconfig, create_case, prep, create_vtk, bladeloading

rule all:
    input :
        #get_casefiles(),
        #get_defined_sim(),
        #get_results(),
        get_post()
