image: continuumio/miniconda

before_script:
  - conda init
  - source ~/.bashrc
  - conda update -n base -c defaults conda
  - conda install -n base -c conda-forge mamba
  - mamba create -c conda-forge -c bioconda -n snakemake snakemake
  - conda activate snakemake

#test_linting:
#  stage: test
#  script:
#    - snakemake --lint

test_dryrun:
  stage: test
  script:
    - snakemake -n
