mesh: "resources/mesh/fluent.msh"
env: "set +euo pipefail;source  /opt/OpenFOAM/setImage_v2006.sh ;set -euo pipefail;"
processors: 10
deltat: 0.00000005
courantnumber: 1
endtime: 0.001
writeinterval: 0.0001
