mesh: "resources/mesh/fluent.msh"
env: "set +euo pipefail;.  /opt/OpenFOAM/OpenFOAM-v2006/etc/bashrc ;set -euo pipefail;"
processors: 10
deltat: 0.00000005
courantnumber: 1
endtime: 0.001
writeinterval: 0.0001
