$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  case_type:
    type: string
    pattern : openfoamCompressorCascadeRas
  mesh:
    type: string
  env:
    description: environment commands for prep
    type: string
  prep:
    description: commands to be executed to merge ascii-files with a computational mesh to an executable simulation
    type: string
  prexec:
    description: stuff to do before mpirun
    tyoe: string
    default: ""
  execute:
    description: commands to run a simulation
    type: string
  processors:
    description: nop
    type: number


required:
    - case_type
    - mesh
    - env
    - prep
    - execute