$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  mesh:
    type: string
  processors:
    description: nop
    type: number
  writeinterval:
    description: nop
    type: number
  deltat:
    description: nop
    type: number
  endtime:
    description: nop
    type: number
  courantnumber:
    description: nop
    type: number

additionalProperties: false

required:
    - courantnumber
    - mesh
    - processors