$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  case_type:
    type: string
    pattern : openfoamCompressorCascadeRas
  param_schema:
    type: string
    pattern: "../schemas/openfoamCompressorCascadeRas/openfoamCompressorCascadeRas_param.schema.yaml"
    default: "../schemas/openfoamCompressorCascadeRas/openfoamCompressorCascadeRas_param.schema.yaml"
  option_schema:
    type: string
    pattern: "../schemas/openfoamCompressorCascadeRas/openfoamCompressorCascadeRas_option.schema.yaml"
    default: "../schemas/openfoamCompressorCascadeRas/openfoamCompressorCascadeRas_option.schema.yaml"

additionalProperties: false
