restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
use-singularity: True
rerun-incomplete: True

# Example resource configuration
default-resources:
  - runtime=100
  - mem_mb=12000
  - disk_mb=1000000
  - nodes=1
#  - ntasks_per_node=1
# # set-threads: map rule names to threads
#set-threads:
   #- execute=10
# # set-resources: map rule names to resources in general
set-resources:
   - execute:nodes=1
